"""Builds GroupXX_milestone_presentation.pptx with 8 slides for the 5-minute
milestone talk. Uses the figures generated by _eda_and_baselines.py."""
from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

REPO = Path(__file__).resolve().parent.parent
FIG  = REPO / "milestone" / "figures"
OUT  = REPO / "milestone" / "GroupXX_milestone_presentation.pptx"

prs = Presentation()
prs.slide_width  = Inches(13.333)
prs.slide_height = Inches(7.5)
BLANK = prs.slide_layouts[6]

NAVY = RGBColor(0x0B, 0x3D, 0x91)
GREY = RGBColor(0x44, 0x44, 0x44)


def add_slide():
    return prs.slides.add_slide(BLANK)


def add_text(slide, left, top, width, height, text, *, size=18, bold=False,
             color=GREY, align=PP_ALIGN.LEFT, italic=False):
    tb = slide.shapes.add_textbox(left, top, width, height)
    tf = tb.text_frame
    tf.word_wrap = True
    lines = text if isinstance(text, list) else [text]
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        run = p.add_run()
        run.text = line
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.italic = italic
        run.font.color.rgb = color
        run.font.name = "Calibri"
    return tb


def title_bar(slide, title):
    add_text(slide, Inches(0.4), Inches(0.25), Inches(12.5), Inches(0.8),
             title, size=30, bold=True, color=NAVY)
    # Thin rule
    from pptx.shapes.connector import Connector
    line = slide.shapes.add_connector(1, Inches(0.4), Inches(1.0),
                                      Inches(12.9), Inches(1.0))
    line.line.color.rgb = NAVY
    line.line.width = Pt(1.2)


def footer(slide, page, total):
    add_text(slide, Inches(11.7), Inches(7.0), Inches(1.4), Inches(0.3),
             f"{page} / {total}", size=10, color=GREY, align=PP_ALIGN.RIGHT)
    add_text(slide, Inches(0.4), Inches(7.0), Inches(6), Inches(0.3),
             "GroupXX — SemEval-2026 Task 5 Milestone", size=10, color=GREY)


def add_notes(slide, text):
    slide.notes_slide.notes_text_frame.text = text


TOTAL = 10

# --- Slide 1: Title -------------------------------------------------------
s = add_slide()
add_text(s, Inches(0.5), Inches(2.2), Inches(12.3), Inches(1.2),
         "Rating Plausibility of Word Senses in Ambiguous Sentences",
         size=40, bold=True, color=NAVY, align=PP_ALIGN.CENTER)
add_text(s, Inches(0.5), Inches(3.4), Inches(12.3), Inches(0.7),
         "through Narrative Understanding — SemEval-2026 Task 5",
         size=22, italic=True, color=GREY, align=PP_ALIGN.CENTER)
add_text(s, Inches(0.5), Inches(4.4), Inches(12.3), Inches(0.7),
         "GroupXX — Milestone Presentation",
         size=20, bold=True, color=GREY, align=PP_ALIGN.CENTER)
add_text(s, Inches(0.5), Inches(5.0), Inches(12.3), Inches(0.5),
         "Member 1 · Member 2 · Member 3",
         size=16, color=GREY, align=PP_ALIGN.CENTER)
add_text(s, Inches(0.5), Inches(5.7), Inches(12.3), Inches(0.5),
         "13 April 2026",
         size=14, color=GREY, align=PP_ALIGN.CENTER)
footer(s, 1, TOTAL)
add_notes(s, "Hi, we're GroupXX. Over the next 5 minutes we'll walk through our "
             "milestone on SemEval-2026 Task 5. I'll cover the task, the data, our "
             "proposed approach and our workload split.")

# --- Slide 2: Task ---------------------------------------------------------
s = add_slide()
title_bar(s, "The task: plausibility rating, not selection")
add_text(s, Inches(0.5), Inches(1.25), Inches(12.3), Inches(0.6),
         "Expected system: a function  f(story, homonym, candidate_sense) → rating ∈ {1, 2, 3, 4, 5}",
         size=17, bold=True, color=NAVY)
add_text(s, Inches(0.5), Inches(1.9), Inches(12.3), Inches(2.4), [
    "• Input  = 5-sentence story (precontext · target sentence · ending) + homonym + one candidate gloss.",
    "• Output = integer Likert rating 1 (not plausible) … 5 (very plausible).",
    "• Multiple senses may be simultaneously plausible — unlike classical single-label WSD.",
    "• Metrics (official scoring.py): Spearman ρ vs. human averages + accuracy@std (within 1 σ or |err|<1).",
    "• 'Good' threshold: ρ ≥ 0.7, acc@std ≥ 0.8.",
], size=17)
# A tiny example box
add_text(s, Inches(0.5), Inches(4.6), Inches(12.3), Inches(0.4),
         "Example",
         size=16, bold=True, color=NAVY)
add_text(s, Inches(0.5), Inches(5.0), Inches(12.3), Inches(2.0), [
    "homonym: track     candidate sense: a pair of parallel rails",
    "story: The detectives arrived at the abandoned train station … They followed the track. They began to run along the abandoned railway line.",
    "human choices: 4, 5, 3, 1, 5 → average 3.6, σ = 1.67",
], size=15, italic=True, color=GREY)
footer(s, 2, TOTAL)
add_notes(s, "The task reframes WSD: instead of picking one correct sense, we rate each candidate sense from 1 to 5. "
             "The official scorer uses Spearman correlation against human averages and accuracy@std.")

# --- Slide 3: Task dataset + I/O ------------------------------------------
s = add_slide()
title_bar(s, "Task dataset — AmbiStory  (splits, schema, I/O)")
add_text(s, Inches(0.4), Inches(1.25), Inches(6.4), Inches(0.5),
         "Splits (pre-released by task organisers):", size=15, bold=True, color=NAVY)
add_text(s, Inches(0.4), Inches(1.7), Inches(6.4), Inches(1.8), [
    "• train 2 280   |   dev 588   |   test 930",
    "• unique homonyms: 220 / 55 / 87",
    "• dev ∩ train = 0     test ∩ train = 1   (near-strict homonym split)",
    "• 5 annotators × N  → 18 990 Likert votes total.  seed = 42 everywhere.",
], size=14)
add_text(s, Inches(0.4), Inches(3.7), Inches(6.4), Inches(0.5),
         "Formal I/O contract:", size=15, bold=True, color=NAVY)
add_text(s, Inches(0.4), Inches(4.2), Inches(6.4), Inches(2.4), [
    "input  x = (precontext, sentence, ending, homonym, judged_meaning)",
    "output y ∈ {1, 2, 3, 4, 5}",
    "submission: JSONL line  {\"id\": \"<id>\", \"prediction\": <int>}",
    "",
    "Metrics (scoring.py):  Spearman ρ + accuracy@std",
    "(prediction within 1 σ of mean OR |err| < 1).",
], size=13)
s.shapes.add_picture(str(FIG / "fig1_avg_rating_hist.png"),
                     Inches(6.9), Inches(1.4), width=Inches(6.2))
footer(s, 3, TOTAL)
add_notes(s, "The organisers already provide train/dev/test. The dev split shares zero homonyms with train — "
             "strict generalisation. Formal I/O: five string fields in, one integer 1-5 out, JSONL submission. "
             "Seed 42 for every internal hold-out we carve.")

# --- Slide 4: Additional datasets + augmentation (IMPLEMENTED) ------------
s = add_slide()
title_bar(s, "Additional datasets & augmentation — implemented")
add_text(s, Inches(0.4), Inches(1.2), Inches(6.3), Inches(0.5),
         "Extra corpora (train-time only)", size=15, bold=True, color=NAVY)
add_text(s, Inches(0.4), Inches(1.7), Inches(6.3), Inches(4.6), [
    "✓ WordNet 3.0  (LREC via NLTK)  — implemented",
    "    6 066 lemma+gloss pool for augmentation.",
    "✓ WiC — Word-in-Context  (NAACL 2019)  — implemented",
    "    20 / 54 dev homonyms covered → 160 pseudo-entries.",
    "",
    "Planned (final deliverable):",
    "• CoarseWSD-28  (EMNLP 2020) — gloss-informed pre-training.",
    "• SemCor 3.0  (LREC 1998) — masked-LM continued pre-training.",
], size=13)
add_text(s, Inches(6.8), Inches(1.2), Inches(6.3), Inches(0.5),
         "Augmentation outputs on train (real counts)", size=15, bold=True, color=NAVY)
add_text(s, Inches(6.8), Inches(1.7), Inches(6.3), Inches(4.6), [
    "✓ WordNet synonym-swap     → +1 660 samples",
    "✓ WordNet gloss paraphrase → +2 232 samples",
    "✓ Likert mix-up (KL<0.1)   →   +517 samples",
    "✓ WiC pseudo-entries       →   +160 samples",
    "   pool grows 2 280 → 6 849  (+200 %)",
    "",
    "Sentence back-translation → deferred (MarianMT DL).",
], size=13)
add_text(s, Inches(0.4), Inches(6.4), Inches(12.6), Inches(0.6),
         "Leakage safeguard: no AmbiStory dev/test homonym is used as a label source; seed 42 everywhere.",
         size=13, italic=True, color=GREY)
footer(s, 4, TOTAL)
add_notes(s, "Unlike a typical milestone, we already ran the augmentation and the additional-dataset integration. "
             "WordNet adds nearly 4000 augmented samples, WiC covers 20 dev homonyms, pool triples in size. "
             "The real effect on dev is on the next-to-last slide.")

# --- Slide 5: EDA ---------------------------------------------------------
s = add_slide()
title_bar(s, "EDA highlights")
s.shapes.add_picture(str(FIG / "fig2_stdev_hist.png"),
                     Inches(0.4), Inches(1.3), width=Inches(6.2))
s.shapes.add_picture(str(FIG / "fig4_top_homonyms.png"),
                     Inches(6.9), Inches(1.3), width=Inches(6.0))
add_text(s, Inches(0.4), Inches(5.7), Inches(12.6), Inches(1.3), [
    "• High annotator disagreement (mean σ = 0.95) caps achievable accuracy@std.",
    "• Narrative is short — the 5 sentences fit in a 256-token window.",
    "• 'nonsensical' flag drops from 14 % at rating ≤ 2 to 3 % at rating > 4 → informative auxiliary signal.",
], size=15)
footer(s, 5, TOTAL)
add_notes(s, "Annotators disagree quite a lot — σ averages 0.95. That caps accuracy@std because some variance just isn't learnable. "
             "The nonsensical flag correlates inversely with rating, a free auxiliary signal we may use.")

# --- Slide 6: Related work ------------------------------------------------
s = add_slide()
title_bar(s, "Related work — five papers from allowed venues")
add_text(s, Inches(0.5), Inches(1.3), Inches(12.3), Inches(5.0), [
    "• Devlin et al., BERT (NAACL 2019). Pre-trained encoder used as our fine-tune backbone.",
    "• Brown et al., GPT-3 (NeurIPS 2020). In-context few-shot learning for semantic classification.",
    "• Blevins & Zettlemoyer, Gloss-Informed Biencoders (ACL 2020). Concatenating gloss with context — directly inspires our RoBERTa input format.",
    "• Loureiro & Jorge, LMMS (ACL 2019). Contextual embedding nearest-sense baseline; motivates ensembling.",
    "• Pilehvar & Camacho-Collados, WiC (NAACL 2019). Candidate augmentation corpus — integrated in §4.",
], size=18)
footer(s, 6, TOTAL)
add_notes(s, "These are the five papers we rely on. All from rubric-allowed venues.")

# --- Slide 7: Approach ----------------------------------------------------
s = add_slide()
title_bar(s, "Proposed approach — four methods + ensemble")
add_text(s, Inches(0.4), Inches(1.20), Inches(12.5), Inches(0.5),
         "Input: story (precontext · sentence · ending)  +  homonym + candidate gloss   →   rating 1–5",
         size=15, italic=True, color=NAVY)
add_text(s, Inches(0.4), Inches(1.75), Inches(6.3), Inches(5.2), [
    "(a) LLM prompting",
    "• Zero-shot + few-shot (4 SBERT-retrieved examples).",
    "• Strong world knowledge, no training.",
    "",
    "(b) Encoder regression (MSE)",
    "• RoBERTa / DeBERTa-v3 + linear head on [CLS].",
    "• Input:  <s> sentence </s> homonym : gloss </s> precontext + ending",
    "• Gloss-informed (Blevins & Zettlemoyer, ACL 2020).",
], size=15)
add_text(s, Inches(6.9), Inches(1.75), Inches(6.3), Inches(5.2), [
    "(c) Ordinal regression head  ★ novel",
    "• Four monotone thresholds on [CLS], CORN loss.",
    "• Handles the ordinal Likert scale.",
    "",
    "(d) Likert distribution head  ★ novel",
    "• Predicts P(choice=k | story, gloss), KL-div vs 5 annotators.",
    "• Exposes per-sample uncertainty → instance-wise ensemble.",
], size=15)
add_text(s, Inches(0.4), Inches(6.5), Inches(12.6), Inches(0.6),
         "(e) Ensemble: calibrated average of (a)+(d) over a homonym-disjoint train hold-out.",
         size=15, bold=True, color=NAVY)
footer(s, 7, TOTAL)
add_notes(s, "Four methods plus an ensemble. (a) and (b) are standard recipes from the cited papers. "
             "(c) and (d) are our novel additions for this task: the ordinal head respects the Likert structure, "
             "and the distribution head captures annotator uncertainty which the scalar 'average' throws away. "
             "The ensemble is calibrated on a homonym-disjoint fold so it matches the real dev regime.")

# --- Slide 8: Code reuse vs. our novel contribution -----------------------
s = add_slide()
title_bar(s, "Reused code vs. our novel contribution")
add_text(s, Inches(0.4), Inches(1.25), Inches(6.2), Inches(0.5),
         "Reused (disclosed)", size=18, bold=True, color=NAVY)
add_text(s, Inches(0.4), Inches(1.8), Inches(6.2), Inches(5.0), [
    "• Official task scorer: scoring.py, format_check.py",
    "• HuggingFace transformers, sentence-transformers",
    "• PyTorch AdamW + linear warm-up",
    "• scikit-learn TfidfVectorizer, Ridge",
    "• scipy.stats.spearmanr",
    "• NLTK WordNet (for our augmentation ops)",
    "• WiC dataset (Pilehvar & Camacho-Collados, NAACL 2019)",
], size=14)
add_text(s, Inches(6.8), Inches(1.25), Inches(6.2), Inches(0.5),
         "Our novel contribution", size=18, bold=True, color=NAVY)
add_text(s, Inches(6.8), Inches(1.8), Inches(6.2), Inches(5.0), [
    "• EDA: dev∩train homonyms = 0  (drives methodology)",
    "• Ordinal-regression head (CORN) for the Likert ladder  ★",
    "• Likert-distribution head (KL-div over 5 annotators)  ★",
    "• Four augmentation ops implemented (notebook §6)  ★",
    "• WiC integration with leakage safeguard  ★",
    "• Narrative-component ablation — does the story help?",
    "• Homonym-disjoint calibration fold; nonsensical aux head",
    "• All baselines, loaders, prompt builder, plots",
], size=13)
add_text(s, Inches(0.4), Inches(6.6), Inches(12.6), Inches(0.5),
         "No code is taken from a paper without citation — every external dependency is disclosed above.",
         size=13, italic=True, color=GREY)
footer(s, 8, TOTAL)
add_notes(s, "We disclose everything we reuse on the left. On the right is what we actually wrote — the EDA insight, the input format, the ablation design, the homonym-disjoint calibration fold, and the auxiliary nonsensical-flag head. None of those five items is taken from a paper.")

# --- Slide 9: Workload + baselines + augmentation effect ------------------
s = add_slide()
title_bar(s, "Workload division & current dev results")
s.shapes.add_picture(str(FIG / "fig11_augmented_vs_baseline.png"),
                     Inches(6.9), Inches(1.3), width=Inches(6.2))
add_text(s, Inches(0.4), Inches(1.3), Inches(6.3), Inches(0.5),
         "Workload (equal share)", size=18, bold=True, color=NAVY)
add_text(s, Inches(0.4), Inches(1.8), Inches(6.3), Inches(2.2), [
    "Member 1 — data pipeline, EDA, LLM prompting.",
    "Member 2 — encoder fine-tune, ordinal + distribution heads.",
    "Member 3 — evaluation, augmentation, WiC, writing.",
], size=14)
add_text(s, Inches(0.4), Inches(4.0), Inches(6.3), Inches(0.5),
         "Dev results so far (our code)", size=18, bold=True, color=NAVY)
add_text(s, Inches(0.4), Inches(4.5), Inches(6.3), Inches(2.8), [
    "majority (=4):              acc 0.57  ρ 0.00",
    "TF-IDF cosine:            acc 0.53  ρ +0.19",
    "Ridge + ordinal:           acc 0.55  ρ +0.11",
    "★ Ridge + WordNet aug:  acc 0.53  ρ +0.15",
    "★ Ridge + mix-up:         acc 0.54  ρ +0.14",
    "★ Ridge + WiC:               acc 0.53  ρ +0.13",
    "",
    "Aug lifts Spearman +0.12 → +0.15  (~25 % rel.)",
], size=12)
footer(s, 9, TOTAL)
add_notes(s, "Our baselines are the first to produce non-zero Spearman. "
             "WordNet augmentation lifts Spearman by 25% relative — from 0.124 to 0.150 — on the same feature set. "
             "Likert mix-up lifts acc@std by one point. "
             "WiC does not help this linear model but is kept in the pipeline as pre-training for the encoder.")

# --- Slide 10: Next steps --------------------------------------------------
s = add_slide()
title_bar(s, "Next steps · Q & A")
add_text(s, Inches(0.5), Inches(1.3), Inches(12.3), Inches(5.5), [
    "Weeks 14–18:",
    "• Week of Apr 14 — zero-shot LLM on dev; first RoBERTa training run.",
    "• Week of Apr 21 — few-shot retrieval + DeBERTa-v3 sweeps; narrative ablation.",
    "• Week of Apr 28 — ensemble calibration; error analysis on high-σ samples.",
    "• Week of May 5  — final runs on test; CodaBench submission.",
    "• Week of May 12 — report, slides, Q&A prep.",
    "",
    "Risks: API cost (budget-cap), GPU availability (fall back to base size), overfitting to glosses.",
], size=18)
add_text(s, Inches(0.5), Inches(6.3), Inches(12.3), Inches(0.7),
         "Thank you — questions?", size=26, bold=True, color=NAVY, align=PP_ALIGN.CENTER)
footer(s, 10, TOTAL)
add_notes(s, "Five-week plan through May 18. Main risks are cost, compute, and overfitting; we have mitigations for each. Thanks — happy to take questions.")

try:
    prs.save(str(OUT))
except PermissionError:
    tmp = OUT.with_suffix(".new.pptx")
    prs.save(str(tmp))
    print(f"WARNING: {OUT.name} is locked (open in PowerPoint?). Wrote {tmp.name} instead.")
    print("Close PowerPoint and rename .new.pptx over the original.")
    raise SystemExit(0)
print("Wrote", OUT)
print("slides:", len(prs.slides))
